config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get '/session' => 'sessions#show'
  get '/ajax' => 'home#ajax', as: 'ajax_home'
  get '/admin' => 'users#admin', as: 'user_admin'
  get '/home' => 'home#ajax'
  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get '/users/:id/edit' => 'users#edit', as: 'edit_user'
  post '/users/:id' => 'users#update'
  delete 'users/delete' => 'users#destroy', as: 'delete_user'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#socialcreate'
  post '/enrollments/new' => 'enrollments#create', as: 'enrollments'
  delete '/enrollments/:id/unenroll' => 'enrollments#destroy', as: 'unenroll'
  get '/available' => 'courses#available' 


  resources :courses 	
  
  resources :teachers do
  	resources :courses, only: [:show, :index, :new] 
  end
end

app/models/User.rb
class User < ActiveRecord::Base
	has_many :enrollments
	has_many :courses, through: :enrollments
	accepts_nested_attributes_for :courses
	validates :name, presence: true
	validates :email, presence: true
	validates :name, uniqueness: true
	validates :email, uniqueness: true
	has_secure_password





end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		if session[:user_id] != nil
		redirect_to "/home"
		else
		@user = User.new
		end
	end

	def admin
		redirect_to "/home" unless isadmin?
		@users = User.all
	end


	def create
		if session[:user_id] != nil 
			redirect_to '/home' 
		else
			@user = User.new(user_params)
				if @user.save
	     		session[:user_id] = @user.id
		 		redirect_to "/home"
	    	else
	     		render :new
			end
		end
	end


	def home
		if session[:user_id] == nil 
			redirect_to '/login' 
		else
			@user = User.find(session[:user_id])
			@online = @user.enrollments.online
			@classroom = @user.enrollments.classroom 
			
		end
	end

	def edit
		redirect_to "/home" unless isadmin?
		@user = User.find(params[:id])
	end

	def update
		redirect_to "/home" unless isadmin?
	    @user = User.find(params[:id])
	    @user.update(user_params)
	    if @user.save
	      flash[:notice] = "#{@user.name} updated."
	      redirect_to "/home"
	    else
	      render :edit
	    end 
	end

	def destroy
		redirect_to "/home" unless isadmin?
		user = User.find(params[:format])
	    user.destroy
	    flash[:notice] = "You have deleted #{user.name}."
	    redirect_to "/home"
	end

	private
	 
	  def user_params
	    params.require(:user).permit(:name, :password, :email, :teacher, :admin)
	  end



end

app/views/users/_validate.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error") %>
      prohibited this user from being signed up:
    </h2>
 
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/admin.html.erb
<h3>Users (<%=@users.count %>)</h3>
<% @users.each do |user| %>
	<%= user.name %><br>
	Email: <%= user.email %><br>
	Admin?: <%= user.admin %><br>
	<% if isadmin? %>
		<%= button_to "Edit User", edit_user_path(user), :method => :get %>
		<%= button_to "Delete User", delete_user_path(user), :method => :delete %><br>
	<% end %>
<% end %>

app/views/users/edit.html.erb
<%= render 'validate'%>
<%= form_for :user, url: "/users/#{@user.id}" do |f| %>
  Username: <%= f.text_field :name %>
  Password: <%= f.password_field :password %>
  Email: <%= f.email_field :email %>
  Admin: <%= f.check_box :admin, {}, "true", "false" %>
  <%= f.submit %>
<% end %>

app/views/users/home.html.erb
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>

<img src="<%= @user.image %>">
<h1>Hello, <%= @user.name %>!</h1>
    Email: <%= @user.email %> <br>

<% if !isadmin? %>
    <h2>Your Courses (<%=@user.enrollments.count %>)</h2>
    <h3>Online Courses (<%=@online.count %>)</h3>
    <% @online.each do |enrollment| %>
        <% if enrollment.course_id_check %>
	       <% course = Course.find(enrollment.course_id) %>
            <b><h3><%= link_to course.name, course_path(course.id) %></h3></b>
            Course Type: <b><%= enrollment.course_type %></b><br>
            Teacher: <em><%= course.teacher_name %><br></em>
            Description:<br> <%= course.description %><br>
        	<%= button_to "Unenroll", unenroll_path(enrollment), :method => :delete %>
        <% end %>
    <% end %>

    <h3>Classroom Courses (<%=@classroom.count %>)</h3>
    <% @classroom.each do |enrollment| %>
        <% if enrollment.course_id_check %>
        	<% course = Course.find(enrollment.course_id) %>
            <b><h3><%= link_to course.name, course_path(course.id) %></h3></b>
            Course Type: <b><%= enrollment.course_type %></b><br>
            Teacher: <em><%= course.teacher_name %><br></em>
            Description:<br> <%= course.description %><br>
            <%= button_to "Unenroll", unenroll_path(enrollment), :method => :delete %>
        <% end %>
    <% end %>
<% end %>
<br>
<% if isadmin? %>
    <%= button_to "User Admin", user_admin_path, :method => :get %>
<% end %>

app/views/users/new.html.erb
<%= render 'validate'%>



<%= form_for :user, url: '/users' do |f| %>
  Username: <%= f.text_field :name %>
  Password: <%= f.password_field :password %>
  Email: <%= f.email_field :email %>
  Admin: <%= f.check_box :admin, {}, "true", "false" %>
  <%= f.submit "Sign Up" %>
<% end %><br>
Existing user log in: <button onclick='window.location.href="/login";'>Log in</button><br>
<h2> <%= link_to('Log in with Facebook!', '/auth/facebook') %></h2>