config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  get '/session' => 'sessions#show'
  get '/ajax' => 'home#ajax', as: 'ajax_home'
  get '/admin' => 'users#admin', as: 'user_admin'
  get '/home' => 'home#ajax'
  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get '/users/:id/edit' => 'users#edit', as: 'edit_user'
  post '/users/:id' => 'users#update'
  delete 'users/delete' => 'users#destroy', as: 'delete_user'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#socialcreate'
  post '/enrollments/new' => 'enrollments#create', as: 'enrollments'
  delete '/enrollments/:id/unenroll' => 'enrollments#destroy', as: 'unenroll'
  get '/available' => 'courses#available' 


  resources :courses 	
  
  resources :teachers do
  	resources :courses, only: [:show, :index, :new] 
  end
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	has_many :courses
	has_many :enrollments, through: :courses
	validates :name, presence: true
	validates :name, uniqueness: true

	scope :id_check, -> (teacherid) { where("id == ? ", teacherid)}


end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController

  def new
  	redirect_to "/home" unless isadmin?
    @teacher = Teacher.new
  end

  def create
  	redirect_to "/home" unless isadmin?
  	@teacher = Teacher.new(teacher_params)
  	if @teacher.save
        redirect_to teacher_path(@teacher)
    else
        render :new
  	end
  end

  def index
  	@teachers = Teacher.all
  end


  def show
  	@teacher = Teacher.find(params[:id])
    respond_to do |format|
          format.html { render :show }
          format.json { render json: @teacher, status: 200} 
    end
  end

  def edit
  	redirect_to "/home" unless isadmin?
  	@teacher = Teacher.find(params[:id])
  end

  def update
  	redirect_to "/home" unless isadmin?
    @teacher = Teacher.find(params[:id])

    @teacher.update(teacher_params)

    if @teacher.save
      redirect_to @teacher
    else
      render :edit
    end  
  end

  def destroy
  	redirect_to "/home" unless isadmin?
  	teacher = Teacher.find(params[:id])
    teacher.destroy
    redirect_to "/teachers"
  end


  private
  
    def teacher_params
      params.require(:teacher).permit(:name)
    end
end

app/views/teachers/_form.html.erb
<% if @teacher.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@teacher.errors.count, "error") %>
      prohibited this teacher from being saved:
    </h2>
 
    <ul>
    <% @teacher.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= form_for @teacher do |f| %>
  <%= f.label "Name" %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/teachers/edit.html.erb
<%= render 'form'%>

app/views/teachers/index.html.erb
<h1>All Teachers</h1>
  
<% @teachers.each do |teacher| %>
	<%= link_to "#{teacher.name}", teacher_path(teacher) %><br>
<% end %>

app/views/teachers/new.html.erb
<%= render 'form'%>

app/views/teachers/show.html.erb
<h1><%= @teacher.name %></h1>
<%= link_to "See all courses by #{@teacher.name}", teacher_courses_path(@teacher) %><br>
<% if isadmin? %>
	<%= link_to "Create a course by #{@teacher.name}", new_teacher_course_path(@teacher) %><br>
	<%= button_to "Delete Teacher", @teacher, :method => :delete %>
	<%= button_to "Edit Teacher", edit_teacher_path(@teacher), :method => :get %>
<% end %>